### ISSUE TITLE
Not able to start, webpack-dev-server error

### ISSUE THREAD

**Issue by sasweb** [sasha240100/react-rectangle-popup-menu#2]
My steps:

+ git clone https://github.com/sasha240100/react-rectangle-popup-menu.git
+ cd react-rectangle-popup-menu
+ npm install
+ npm start

Expected:
Project runs.

Actual:
`./node_modules/.bin/webpack-dev-server: No such file or directory`

For me, the start script "(npm run watch & npm run examples:watch)" makes no sense. There is no watch script in examples/package.json.

Node version: 8.11.3

**Comment by RickyTB** [comment]
I had the same problem. Turns out you have to cd into examples and npm install there as well. After that go up one level and npm start again.

**Comment by sasha240100** [comment]
@pawelsas Can I close this issue accounting @RickyTB comment as an answer?

**Comment by sasweb** [comment]
Yes, thanks!
